# Site settings
title: Joshua Goodwin
description: His blog
email: j@joshuagoodw.in
url: "https://joshuagoodw.in" # the base hostname & protocol for your site

permalink: /:year/:month/:title
paginate: 5
paginate_path: "/page/:num"

sass:
  style: :compressed

compress_html:
  clippings: all